---

- name: Checkout repository
  git:
    repo: "{{ repository }}"
    dest: "{{ checkout_path }}"
    accept_hostkey: yes
    key_file: /root/.ssh/id_rsa

- name: Import DB dump from Platform Init repository
  mysql_db:
    state: import
    name: all
    target: "{{ checkout_path }}/SQL/{{ item }}"
  with_items: "{{mysql_scripts}}"
